"""Initial migration

Revision ID: dabaefb42760
Revises: 
Create Date: 2024-04-09 16:02:20.296435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dabaefb42760'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dlc_neural_network',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('started_training_at', sa.DateTime(), nullable=True),
    sa.Column('finished_training_at', sa.DateTime(), nullable=True),
    sa.Column('training_config', sa.String(), nullable=False),
    sa.Column('network_folder_path', sa.String(), nullable=False),
    sa.Column('currently_training', sa.Boolean(), nullable=False),
    sa.Column('celery_training_task_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('inference_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('results_json', sa.String(), nullable=True),
    sa.Column('started_inference_at', sa.DateTime(), nullable=True),
    sa.Column('finished_inference_at', sa.DateTime(), nullable=True),
    sa.Column('currently_running_inference', sa.Boolean(), nullable=False),
    sa.Column('sent_back', sa.Boolean(), nullable=False),
    sa.Column('network_uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['network_uid'], ['dlc_neural_network.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inference_results')
    op.drop_table('dlc_neural_network')
    # ### end Alembic commands ###
